[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = [
  "cd faceprep && npm install && npm run build",
  "cd faceprep-backend && npm install"
]

[start]
cmd = "node faceprep-backend/src/server.js"