[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gnumake", "gcc"]

[phases.build]
cmds = [
  "cd faceprep && npm install && npm run build",
  "cd faceprep-backend && npm install --build-from-source"
]

[start]
cmd = "node faceprep-backend/src/server.js"